server:
  port: 9060


spring:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://0.0.0.0:3306/onlineexam?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Seoul
    username: spark
    password: flamerz801

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  thymeleaf:
    prefix: classpath:/templates/
    cache: false
    check-template-location: true
    suffix: .html

#logging:
#  level:
#    org.springframework.web: true